[2020-05-11 00:30:19,919] WARNING MainProcess urls.py:63 >>>>>>>>>>>Base url : http://127.0.0.1:8000<<<
[2020-05-11 00:30:20,381] WARNING MainProcess views.py:65 check file exists:C:\Progetti\SitiWeb\IlViale\media\il_viale_rss_payload.rss
[2020-05-11 00:30:20,388] WARNING MainProcess views.py:80 renaming:C:\Progetti\SitiWeb\IlViale\media\il_viale_rss_payload.rss in:C:\Progetti\SitiWeb\IlViale\media\il_viale_rss_payload20200511_003020.384630.rss
[2020-05-11 00:30:21,496] INFO MainProcess basehttp.py:154 "GET /BlogView/ HTTP/1.1" 200 87714
[2020-05-11 00:30:21,802] WARNING MainProcess urls.py:63 >>>>>>>>>>>Base url : http://127.0.0.1:8000<<<
[2020-05-11 00:30:21,830] WARNING MainProcess basehttp.py:154 "GET /static/images/bg-main.jpg HTTP/1.1" 404 1779
[2020-05-11 00:30:22,339] WARNING MainProcess urls.py:63 >>>>>>>>>>>Base url : http://127.0.0.1:8000<<<
[2020-05-11 00:30:22,350] INFO MainProcess basehttp.py:154 "GET /static/images/favicon.ico HTTP/1.1" 200 15086
[2020-05-11 00:32:30,385] WARNING MainProcess urls.py:75 >>>>>>>>>>>SERVER_TYPEDEVHOME
[2020-05-11 00:32:30,390] WARNING MainProcess urls.py:83 >>>>>>>>>>>Error Base Url:http://127.0.0.1:8000
[2020-05-11 00:32:30,430] INFO MainProcess basehttp.py:154 "GET / HTTP/1.1" 301 0
[2020-05-11 00:32:32,441] INFO MainProcess basehttp.py:154 "GET /BlogView/ HTTP/1.1" 200 87714
[2020-05-11 00:32:32,829] WARNING MainProcess basehttp.py:154 "GET /static/images/bg-main.jpg HTTP/1.1" 404 1779
[2020-05-11 00:35:24,215] INFO MainProcess basehttp.py:154 "GET /BlogView/ HTTP/1.1" 200 87714
[2020-05-11 00:35:24,582] WARNING MainProcess basehttp.py:154 "GET /static/images/bg-main.jpg HTTP/1.1" 404 1779
[2020-05-11 00:35:56,458] WARNING MainProcess urls.py:75 >>>>>>>>>>>SERVER_TYPEDEVHOME
[2020-05-11 00:35:56,461] WARNING MainProcess urls.py:83 >>>>>>>>>>>Error Base Url:http://127.0.0.1:8000
[2020-05-11 00:35:56,499] INFO MainProcess basehttp.py:154 "GET / HTTP/1.1" 301 0
[2020-05-11 00:35:58,374] INFO MainProcess basehttp.py:154 "GET /BlogView/ HTTP/1.1" 200 87714
[2020-05-11 00:35:58,729] WARNING MainProcess basehttp.py:154 "GET /static/images/bg-main.jpg HTTP/1.1" 404 1779
[2020-05-11 00:36:53,905] INFO MainProcess basehttp.py:154 "GET /BlogView/ HTTP/1.1" 200 87714
[2020-05-11 00:36:53,995] INFO MainProcess basehttp.py:154 "GET /static/js/rss_tree.js HTTP/1.1" 200 6774
[2020-05-11 00:36:53,996] INFO MainProcess basehttp.py:154 "GET /static/css/TreeView.css HTTP/1.1" 200 1400
[2020-05-11 00:36:54,364] INFO MainProcess basehttp.py:154 "GET /static/images/LogoVialeBianco2019.png HTTP/1.1" 200 60923
[2020-05-11 00:36:54,553] INFO MainProcess basehttp.py:154 "GET /static/images/newsletter.png HTTP/1.1" 200 251693
[2020-05-11 00:36:54,558] INFO MainProcess basehttp.py:154 "GET /static/images/cronologia.png HTTP/1.1" 200 274926
[2020-05-11 00:36:54,563] INFO MainProcess basehttp.py:154 "GET /static/images/QRViale.png HTTP/1.1" 200 395
[2020-05-11 00:36:54,568] INFO MainProcess basehttp.py:154 "GET /static/images/rssLogo.gif HTTP/1.1" 200 1696
[2020-05-11 00:36:54,597] INFO MainProcess basehttp.py:154 "GET /static/images/bg-curve-top-left.gif HTTP/1.1" 200 227
[2020-05-11 00:36:54,626] INFO MainProcess basehttp.py:154 "GET /static/images/bg-curve-bottom-right.gif HTTP/1.1" 200 233
[2020-05-11 00:36:54,632] INFO MainProcess basehttp.py:154 "GET /static/css/images/social.png HTTP/1.1" 200 3145
[2020-05-11 00:36:54,632] INFO MainProcess basehttp.py:154 "GET /static/images/GoogleTranslate.webp HTTP/1.1" 200 9766
[2020-05-11 00:36:54,644] WARNING MainProcess basehttp.py:154 "GET /static/images/bg-main.jpg HTTP/1.1" 404 1779
[2020-05-11 00:36:54,647] INFO MainProcess basehttp.py:154 "GET /static/css/arrowExpand.gif HTTP/1.1" 200 870
[2020-05-11 00:36:55,195] INFO MainProcess basehttp.py:154 "GET /static/images/favicon.ico HTTP/1.1" 200 15086
[2020-05-11 00:38:25,424] WARNING MainProcess urls.py:75 >>>>>>>>>>>SERVER_TYPEDEVHOME
[2020-05-11 00:38:25,439] WARNING MainProcess urls.py:83 >>>>>>>>>>>Error Base Url:http://127.0.0.1:8000
[2020-05-11 00:38:28,013] INFO MainProcess basehttp.py:154 "GET /BlogView/ HTTP/1.1" 200 87714
[2020-05-11 00:38:28,101] INFO MainProcess basehttp.py:154 "GET /static/js/rss_tree.js HTTP/1.1" 200 6774
[2020-05-11 00:38:28,102] INFO MainProcess basehttp.py:154 "GET /static/css/TreeView.css HTTP/1.1" 200 1400
[2020-05-11 00:38:28,466] INFO MainProcess basehttp.py:154 "GET /static/images/LogoVialeBianco2019.png HTTP/1.1" 200 60923
[2020-05-11 00:38:28,517] INFO MainProcess basehttp.py:154 "GET /static/images/newsletter.png HTTP/1.1" 200 251693
[2020-05-11 00:38:28,518] INFO MainProcess basehttp.py:154 "GET /static/images/cronologia.png HTTP/1.1" 200 274926
[2020-05-11 00:38:28,546] INFO MainProcess basehttp.py:154 "GET /static/images/QRViale.png HTTP/1.1" 200 395
[2020-05-11 00:38:28,574] INFO MainProcess basehttp.py:154 "GET /static/images/bg-curve-top-left.gif HTTP/1.1" 200 227
[2020-05-11 00:38:28,587] INFO MainProcess basehttp.py:154 "GET /static/css/arrowExpand.gif HTTP/1.1" 200 870
[2020-05-11 00:38:28,587] INFO MainProcess basehttp.py:154 "GET /static/css/images/social.png HTTP/1.1" 200 3145
[2020-05-11 00:38:28,589] INFO MainProcess basehttp.py:154 "GET /static/images/bg-curve-bottom-right.gif HTTP/1.1" 200 233
[2020-05-11 00:38:28,614] INFO MainProcess basehttp.py:154 "GET /static/images/rssLogo.gif HTTP/1.1" 200 1696
[2020-05-11 00:38:28,627] INFO MainProcess basehttp.py:154 "GET /static/images/GoogleTranslate.webp HTTP/1.1" 200 9766
[2020-05-11 00:38:28,690] WARNING MainProcess basehttp.py:154 "GET /static/images/bg-main.jpg HTTP/1.1" 404 1779
[2020-05-11 00:38:29,048] INFO MainProcess basehttp.py:154 "GET /static/images/favicon.ico HTTP/1.1" 200 15086
[2020-05-11 00:46:01,633] WARNING MainProcess urls.py:75 >>>>>>>>>>>SERVER_TYPEDEVHOME
[2020-05-11 00:46:01,638] WARNING MainProcess urls.py:83 >>>>>>>>>>>Error Base Url:http://127.0.0.1:8000
[2020-05-11 00:46:01,685] INFO MainProcess basehttp.py:154 "GET / HTTP/1.1" 301 0
[2020-05-11 00:46:03,675] INFO MainProcess basehttp.py:154 "GET /BlogView/ HTTP/1.1" 200 87714
[2020-05-11 00:46:03,781] INFO MainProcess basehttp.py:154 "GET /static/js/rss_tree.js HTTP/1.1" 200 6774
[2020-05-11 00:46:03,782] INFO MainProcess basehttp.py:154 "GET /static/css/TreeView.css HTTP/1.1" 200 1400
[2020-05-11 00:46:04,187] INFO MainProcess basehttp.py:154 "GET /static/images/LogoVialeBianco2019.png HTTP/1.1" 200 60923
[2020-05-11 00:46:04,191] INFO MainProcess basehttp.py:154 "GET /static/images/newsletter.png HTTP/1.1" 200 251693
[2020-05-11 00:46:04,225] INFO MainProcess basehttp.py:154 "GET /static/images/cronologia.png HTTP/1.1" 200 274926
[2020-05-11 00:46:04,257] WARNING MainProcess basehttp.py:154 "GET /static/images/bg-main.jpg HTTP/1.1" 404 1779
[2020-05-11 00:46:04,266] INFO MainProcess basehttp.py:154 "GET /static/images/bg-curve-top-left.gif HTTP/1.1" 200 227
[2020-05-11 00:46:04,273] INFO MainProcess basehttp.py:154 "GET /static/images/QRViale.png HTTP/1.1" 200 395
[2020-05-11 00:46:04,289] INFO MainProcess basehttp.py:154 "GET /static/css/images/social.png HTTP/1.1" 200 3145
[2020-05-11 00:46:04,315] INFO MainProcess basehttp.py:154 "GET /static/images/bg-curve-bottom-right.gif HTTP/1.1" 200 233
[2020-05-11 00:46:04,334] INFO MainProcess basehttp.py:154 "GET /static/css/arrowExpand.gif HTTP/1.1" 200 870
[2020-05-11 00:46:04,342] INFO MainProcess basehttp.py:154 "GET /static/images/rssLogo.gif HTTP/1.1" 200 1696
[2020-05-11 00:46:04,360] INFO MainProcess basehttp.py:154 "GET /static/images/GoogleTranslate.webp HTTP/1.1" 200 9766
[2020-05-11 00:46:05,039] INFO MainProcess basehttp.py:154 "GET /static/images/favicon.ico HTTP/1.1" 200 15086
[2020-05-11 00:49:02,519] WARNING MainProcess urls.py:75 >>>>>>>>>>>SERVER_TYPEDEVHOME
[2020-05-11 00:49:02,524] WARNING MainProcess urls.py:83 >>>>>>>>>>>Error Base Url:http://127.0.0.1:8000
[2020-05-11 00:49:04,491] INFO MainProcess basehttp.py:154 "GET /BlogView/ HTTP/1.1" 200 87714
[2020-05-11 00:49:04,604] INFO MainProcess basehttp.py:154 "GET /static/js/rss_tree.js HTTP/1.1" 200 6774
[2020-05-11 00:49:04,605] INFO MainProcess basehttp.py:154 "GET /static/css/TreeView.css HTTP/1.1" 200 1400
[2020-05-11 00:49:04,875] INFO MainProcess basehttp.py:154 "GET /static/images/LogoVialeBianco2019.png HTTP/1.1" 200 60923
[2020-05-11 00:49:04,929] INFO MainProcess basehttp.py:154 "GET /static/images/cronologia.png HTTP/1.1" 200 274926
[2020-05-11 00:49:04,930] INFO MainProcess basehttp.py:154 "GET /static/images/newsletter.png HTTP/1.1" 200 251693
[2020-05-11 00:49:04,957] INFO MainProcess basehttp.py:154 "GET /static/images/QRViale.png HTTP/1.1" 200 395
[2020-05-11 00:49:04,970] INFO MainProcess basehttp.py:154 "GET /static/images/bg-curve-top-left.gif HTTP/1.1" 200 227
[2020-05-11 00:49:04,976] INFO MainProcess basehttp.py:154 "GET /static/css/images/social.png HTTP/1.1" 200 3145
[2020-05-11 00:49:04,987] INFO MainProcess basehttp.py:154 "GET /static/css/arrowExpand.gif HTTP/1.1" 200 870
[2020-05-11 00:49:04,989] INFO MainProcess basehttp.py:154 "GET /static/images/bg-curve-bottom-right.gif HTTP/1.1" 200 233
[2020-05-11 00:49:05,005] INFO MainProcess basehttp.py:154 "GET /static/images/rssLogo.gif HTTP/1.1" 200 1696
[2020-05-11 00:49:05,031] INFO MainProcess basehttp.py:154 "GET /static/images/GoogleTranslate.webp HTTP/1.1" 200 9766
[2020-05-11 00:49:05,052] INFO MainProcess basehttp.py:154 "GET /static/images/bg-main.jpg HTTP/1.1" 200 3341
[2020-05-11 00:49:05,703] INFO MainProcess basehttp.py:154 "GET /static/images/favicon.ico HTTP/1.1" 200 15086
[2020-05-11 00:49:31,601] INFO MainProcess basehttp.py:154 "GET /BlogView/ HTTP/1.1" 200 87714
[2020-05-11 00:49:31,699] INFO MainProcess basehttp.py:154 "GET /static/css/TreeView.css HTTP/1.1" 200 1400
[2020-05-11 00:49:31,700] INFO MainProcess basehttp.py:154 "GET /static/js/rss_tree.js HTTP/1.1" 200 6774
[2020-05-11 00:49:32,014] INFO MainProcess basehttp.py:154 "GET /static/images/LogoVialeBianco2019.png HTTP/1.1" 200 60923
[2020-05-11 00:49:32,079] INFO MainProcess basehttp.py:154 "GET /static/images/GoogleTranslate.webp HTTP/1.1" 200 9766
[2020-05-11 00:49:32,080] INFO MainProcess basehttp.py:154 "GET /static/images/rssLogo.gif HTTP/1.1" 200 1696
[2020-05-11 00:49:32,080] INFO MainProcess basehttp.py:154 "GET /static/images/QRViale.png HTTP/1.1" 200 395
[2020-05-11 00:49:32,081] INFO MainProcess basehttp.py:154 "GET /static/images/bg-main.jpg HTTP/1.1" 200 3341
[2020-05-11 00:49:32,091] INFO MainProcess basehttp.py:154 "GET /static/images/bg-curve-top-left.gif HTTP/1.1" 200 227
[2020-05-11 00:49:32,092] INFO MainProcess basehttp.py:154 "GET /static/images/cronologia.png HTTP/1.1" 200 274926
[2020-05-11 00:49:32,093] INFO MainProcess basehttp.py:154 "GET /static/images/newsletter.png HTTP/1.1" 200 251693
[2020-05-11 00:49:32,124] INFO MainProcess basehttp.py:154 "GET /static/css/images/social.png HTTP/1.1" 200 3145
[2020-05-11 00:49:32,126] INFO MainProcess basehttp.py:154 "GET /static/css/arrowExpand.gif HTTP/1.1" 200 870
[2020-05-11 00:49:32,126] INFO MainProcess basehttp.py:154 "GET /static/images/bg-curve-bottom-right.gif HTTP/1.1" 200 233
[2020-05-11 00:49:32,514] INFO MainProcess basehttp.py:154 "GET /static/images/favicon.ico HTTP/1.1" 200 15086
[2020-05-11 00:50:22,686] WARNING urls.py:75 >>>>>>>>>>>SERVER_TYPEDEVHOME
[2020-05-11 00:50:22,691] WARNING urls.py:83 >>>>>>>>>>>Error Base Url:http://127.0.0.1:8000
[2020-05-11 00:50:22,744] INFO basehttp.py:154 "GET / HTTP/1.1" 301 0
[2020-05-11 00:50:24,741] INFO basehttp.py:154 "GET /BlogView/ HTTP/1.1" 200 87714
[2020-05-11 00:50:24,858] INFO basehttp.py:154 "GET /static/js/rss_tree.js HTTP/1.1" 200 6774
[2020-05-11 00:50:24,858] INFO basehttp.py:154 "GET /static/css/TreeView.css HTTP/1.1" 200 1400
[2020-05-11 00:50:25,191] INFO basehttp.py:154 "GET /static/images/LogoVialeBianco2019.png HTTP/1.1" 200 60923
[2020-05-11 00:50:25,239] INFO basehttp.py:154 "GET /static/images/cronologia.png HTTP/1.1" 200 274926
[2020-05-11 00:50:25,242] INFO basehttp.py:154 "GET /static/images/newsletter.png HTTP/1.1" 200 251693
[2020-05-11 00:50:25,246] INFO basehttp.py:154 "GET /static/images/QRViale.png HTTP/1.1" 200 395
[2020-05-11 00:50:25,267] INFO basehttp.py:154 "GET /static/images/rssLogo.gif HTTP/1.1" 200 1696
[2020-05-11 00:50:25,288] INFO basehttp.py:154 "GET /static/images/bg-curve-top-left.gif HTTP/1.1" 200 227
[2020-05-11 00:50:25,289] INFO basehttp.py:154 "GET /static/css/arrowExpand.gif HTTP/1.1" 200 870
[2020-05-11 00:50:25,290] INFO basehttp.py:154 "GET /static/css/images/social.png HTTP/1.1" 200 3145
[2020-05-11 00:50:25,295] INFO basehttp.py:154 "GET /static/images/GoogleTranslate.webp HTTP/1.1" 200 9766
[2020-05-11 00:50:25,308] INFO basehttp.py:154 "GET /static/images/bg-curve-bottom-right.gif HTTP/1.1" 200 233
[2020-05-11 00:50:25,330] INFO basehttp.py:154 "GET /static/images/bg-main.jpg HTTP/1.1" 200 3341
[2020-05-11 20:58:54,175] WARNING urls.py:63 new request
[2020-05-11 20:58:54,186] WARNING urls.py:76 >>>>>>>>>>>SERVER_TYPEDEVHOME
[2020-05-11 20:58:54,189] WARNING urls.py:84 >>>>>>>>>>>Error Base Url:http://127.0.0.1:8000
[2020-05-11 20:58:54,248] INFO basehttp.py:154 "GET / HTTP/1.1" 301 0
[2020-05-11 20:58:54,308] WARNING urls.py:63 new request
[2020-05-11 20:58:56,525] INFO basehttp.py:154 "GET /BlogView/ HTTP/1.1" 200 87714
[2020-05-11 20:58:56,916] WARNING urls.py:63 new request
[2020-05-11 20:58:56,924] INFO basehttp.py:154 "GET /static/images/LogoVialeBianco2019.png HTTP/1.1" 304 0
[2020-05-11 20:59:01,821] WARNING urls.py:63 new request
[2020-05-11 20:59:01,943] INFO basehttp.py:154 "GET /info/storia HTTP/1.1" 200 14408
[2020-05-11 20:59:41,585] WARNING urls.py:63 new request
[2020-05-11 20:59:41,713] INFO basehttp.py:154 "GET /info/storia HTTP/1.1" 200 14424
[2020-05-11 20:59:42,037] WARNING urls.py:63 new request
[2020-05-11 20:59:42,046] WARNING urls.py:63 new request
[2020-05-11 20:59:42,049] INFO basehttp.py:154 "GET /static/images/LogoVialeBianco2019.png HTTP/1.1" 200 60923
[2020-05-11 20:59:42,064] WARNING urls.py:63 new request
[2020-05-11 20:59:42,070] INFO basehttp.py:154 "GET /static/images/bg-main.jpg HTTP/1.1" 200 3341
[2020-05-11 20:59:42,079] INFO basehttp.py:154 "GET /static/images/rssLogo.gif HTTP/1.1" 200 1696
[2020-05-11 20:59:42,082] WARNING urls.py:63 new request
[2020-05-11 20:59:42,098] WARNING urls.py:63 new request
[2020-05-11 20:59:42,105] WARNING urls.py:63 new request
[2020-05-11 20:59:42,118] INFO basehttp.py:154 "GET /static/images/GoogleTranslate.webp HTTP/1.1" 200 9766
[2020-05-11 20:59:42,127] INFO basehttp.py:154 "GET /static/images/bg-curve-top-left.gif HTTP/1.1" 200 227
[2020-05-11 20:59:42,135] INFO basehttp.py:154 "GET /static/images/bg-curve-bottom-right.gif HTTP/1.1" 200 233
[2020-05-11 20:59:42,337] WARNING urls.py:63 new request
[2020-05-11 20:59:42,344] INFO basehttp.py:154 "GET /static/images/favicon.ico HTTP/1.1" 200 15086
[2020-05-11 21:05:23,664] WARNING urls.py:63 new request
[2020-05-11 21:05:25,994] INFO basehttp.py:154 "GET /BlogView/ HTTP/1.1" 200 87714
[2020-05-11 21:05:26,115] WARNING urls.py:63 new request
[2020-05-11 21:05:26,116] WARNING urls.py:63 new request
[2020-05-11 21:05:26,122] INFO basehttp.py:154 "GET /static/js/rss_tree.js HTTP/1.1" 200 6774
[2020-05-11 21:05:26,124] INFO basehttp.py:154 "GET /static/css/TreeView.css HTTP/1.1" 200 1400
[2020-05-11 21:05:26,439] WARNING urls.py:63 new request
[2020-05-11 21:05:26,444] WARNING urls.py:63 new request
[2020-05-11 21:05:26,447] INFO basehttp.py:154 "GET /static/images/LogoVialeBianco2019.png HTTP/1.1" 200 60923
[2020-05-11 21:05:26,459] INFO basehttp.py:154 "GET /static/images/newsletter.png HTTP/1.1" 200 251693
[2020-05-11 21:05:26,462] WARNING urls.py:63 new request
[2020-05-11 21:05:26,468] WARNING urls.py:63 new request
[2020-05-11 21:05:26,475] INFO basehttp.py:154 "GET /static/images/bg-main.jpg HTTP/1.1" 200 3341
[2020-05-11 21:05:26,477] INFO basehttp.py:154 "GET /static/images/bg-curve-top-left.gif HTTP/1.1" 200 227
[2020-05-11 21:05:26,480] WARNING urls.py:63 new request
[2020-05-11 21:05:26,486] WARNING urls.py:63 new request
[2020-05-11 21:05:26,488] WARNING urls.py:63 new request
[2020-05-11 21:05:26,491] INFO basehttp.py:154 "GET /static/css/images/social.png HTTP/1.1" 200 3145
[2020-05-11 21:05:26,504] WARNING urls.py:63 new request
[2020-05-11 21:05:26,507] INFO basehttp.py:154 "GET /static/css/arrowExpand.gif HTTP/1.1" 200 870
[2020-05-11 21:05:26,508] INFO basehttp.py:154 "GET /static/images/GoogleTranslate.webp HTTP/1.1" 200 9766
[2020-05-11 21:05:26,519] INFO basehttp.py:154 "GET /static/images/bg-curve-bottom-right.gif HTTP/1.1" 200 233
[2020-05-11 21:05:26,527] WARNING urls.py:63 new request
[2020-05-11 21:05:26,534] WARNING urls.py:63 new request
[2020-05-11 21:05:26,542] INFO basehttp.py:154 "GET /static/images/rssLogo.gif HTTP/1.1" 200 1696
[2020-05-11 21:05:26,561] INFO basehttp.py:154 "GET /static/images/QRViale.png HTTP/1.1" 200 395
[2020-05-11 21:05:26,567] WARNING urls.py:63 new request
[2020-05-11 21:05:26,612] INFO basehttp.py:154 "GET /static/images/cronologia.png HTTP/1.1" 200 274926
[2020-05-11 21:05:30,469] WARNING urls.py:63 new request
[2020-05-11 21:05:30,603] INFO basehttp.py:154 "GET /info/storia HTTP/1.1" 200 14422
[2020-05-11 21:05:30,921] WARNING urls.py:63 new request
[2020-05-11 21:05:30,923] WARNING urls.py:63 new request
[2020-05-11 21:05:30,925] WARNING urls.py:63 new request
[2020-05-11 21:05:30,933] INFO basehttp.py:154 "GET /static/images/rssLogo.gif HTTP/1.1" 200 1696
[2020-05-11 21:05:30,934] INFO basehttp.py:154 "GET /static/images/LogoVialeBianco2019.png HTTP/1.1" 200 60923
[2020-05-11 21:05:30,941] INFO basehttp.py:154 "GET /static/images/GoogleTranslate.webp HTTP/1.1" 200 9766
[2020-05-11 21:05:30,944] WARNING urls.py:63 new request
[2020-05-11 21:05:30,946] WARNING urls.py:63 new request
[2020-05-11 21:05:30,953] INFO basehttp.py:154 "GET /static/images/bg-main.jpg HTTP/1.1" 200 3341
[2020-05-11 21:05:30,955] INFO basehttp.py:154 "GET /static/images/bg-curve-top-left.gif HTTP/1.1" 200 227
[2020-05-11 21:05:30,957] WARNING urls.py:63 new request
[2020-05-11 21:05:30,972] INFO basehttp.py:154 "GET /static/images/bg-curve-bottom-right.gif HTTP/1.1" 200 233
[2020-05-21 08:58:56,705] WARNING urls.py:63 new request
[2020-05-21 08:58:56,766] WARNING urls.py:76 >>>>>>>>>>>SERVER_TYPEDEVHOME
[2020-05-21 08:58:56,771] WARNING urls.py:84 >>>>>>>>>>>Error Base Url:http://127.0.0.1:8000
[2020-05-21 08:58:56,824] INFO basehttp.py:154 "GET / HTTP/1.1" 301 0
[2020-05-21 08:58:56,874] WARNING urls.py:63 new request
[2020-05-21 08:58:58,440] WARNING views.py:100 New content, new file created
[2020-05-21 08:58:59,738] INFO basehttp.py:154 "GET /BlogView/ HTTP/1.1" 200 87712
[2020-05-21 08:58:59,803] WARNING urls.py:63 new request
[2020-05-21 08:58:59,805] WARNING urls.py:63 new request
[2020-05-21 08:58:59,825] INFO basehttp.py:154 "GET /static/css/TreeView.css HTTP/1.1" 200 1400
[2020-05-21 08:58:59,829] INFO basehttp.py:154 "GET /static/js/rss_tree.js HTTP/1.1" 200 6774
[2020-05-21 08:59:00,158] WARNING urls.py:63 new request
[2020-05-21 08:59:00,161] WARNING urls.py:63 new request
[2020-05-21 08:59:00,168] INFO basehttp.py:154 "GET /static/images/LogoVialeBianco2019.png HTTP/1.1" 200 60923
[2020-05-21 08:59:00,173] INFO basehttp.py:154 "GET /static/images/newsletter.png HTTP/1.1" 200 251693
[2020-05-21 08:59:00,180] WARNING urls.py:63 new request
[2020-05-21 08:59:00,183] WARNING urls.py:63 new request
[2020-05-21 08:59:00,185] WARNING urls.py:63 new request
[2020-05-21 08:59:00,191] INFO basehttp.py:154 "GET /static/images/QRViale.png HTTP/1.1" 200 395
[2020-05-21 08:59:00,192] INFO basehttp.py:154 "GET /static/images/rssLogo.gif HTTP/1.1" 200 1696
[2020-05-21 08:59:00,202] WARNING urls.py:63 new request
[2020-05-21 08:59:00,208] WARNING urls.py:63 new request
[2020-05-21 08:59:00,211] INFO basehttp.py:154 "GET /static/images/GoogleTranslate.webp HTTP/1.1" 200 9766
[2020-05-21 08:59:00,219] INFO basehttp.py:154 "GET /static/images/cronologia.png HTTP/1.1" 200 274926
[2020-05-21 08:59:00,231] WARNING urls.py:63 new request
[2020-05-21 08:59:00,233] INFO basehttp.py:154 "GET /static/images/bg-main.jpg HTTP/1.1" 200 3341
[2020-05-21 08:59:00,235] WARNING urls.py:63 new request
[2020-05-21 08:59:00,240] WARNING urls.py:63 new request
[2020-05-21 08:59:00,242] INFO basehttp.py:154 "GET /static/images/bg-curve-top-left.gif HTTP/1.1" 200 227
[2020-05-21 08:59:00,259] INFO basehttp.py:154 "GET /static/css/arrowExpand.gif HTTP/1.1" 200 870
[2020-05-21 08:59:00,248] INFO basehttp.py:154 "GET /static/css/images/social.png HTTP/1.1" 200 3145
[2020-05-21 08:59:00,260] WARNING urls.py:63 new request
[2020-05-21 08:59:00,277] INFO basehttp.py:154 "GET /static/images/bg-curve-bottom-right.gif HTTP/1.1" 200 233
[2020-05-21 08:59:01,382] WARNING urls.py:63 new request
[2020-05-21 08:59:01,390] INFO basehttp.py:154 "GET /static/images/favicon.ico HTTP/1.1" 200 15086
[2020-05-21 08:59:13,957] WARNING urls.py:63 new request
[2020-05-21 08:59:15,604] INFO basehttp.py:154 "POST /newsletter/newsletter-del-viale-della-formica/subscribe/ HTTP/1.1" 302 0
[2020-05-21 08:59:15,611] WARNING urls.py:63 new request
[2020-05-21 08:59:15,666] INFO basehttp.py:154 "GET /newsletter/newsletter-del-viale-della-formica/subscribe/email-sent/ HTTP/1.1" 200 10998
[2020-05-21 14:40:58,210] WARNING urls.py:63 new request
[2020-05-21 14:40:58,214] WARNING urls.py:76 >>>>>>>>>>>SERVER_TYPEDEVHOME
[2020-05-21 14:40:58,216] WARNING urls.py:84 >>>>>>>>>>>Error Base Url:http://127.0.0.1:8000
[2020-05-21 14:40:58,250] INFO basehttp.py:154 "GET / HTTP/1.1" 301 0
[2020-05-21 14:40:58,285] WARNING urls.py:63 new request
[2020-05-21 14:41:00,186] INFO basehttp.py:154 "GET /BlogView/ HTTP/1.1" 200 87809
[2020-05-21 14:41:20,525] WARNING urls.py:63 new request
[2020-05-21 14:41:21,539] ERROR views.py:424 Error (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials ch8sm4745256ejb.53 - gsmtp') while submitting email to carlo.folini@hotmail.com.
Traceback (most recent call last):
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\newsletter\views.py", line 421, in form_valid
    self.subscription.send_activation_email(action=self.action)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\newsletter\models.py", line 361, in send_activation_email
    message.send()
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\mail\message.py", line 291, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\mail\backends\smtp.py", line 103, in send_messages
    new_conn_created = self.open()
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\mail\backends\smtp.py", line 70, in open
    self.connection.login(self.username, self.password)
  File "C:\Program Files\Python38\lib\smtplib.py", line 734, in login
    raise last_exception
  File "C:\Program Files\Python38\lib\smtplib.py", line 723, in login
    (code, resp) = self.auth(
  File "C:\Program Files\Python38\lib\smtplib.py", line 646, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials ch8sm4745256ejb.53 - gsmtp')
[2020-05-21 14:41:21,640] INFO basehttp.py:154 "POST /newsletter/newsletter-del-viale-della-formica/subscribe/ HTTP/1.1" 200 11132
[2020-05-21 14:41:46,950] WARNING urls.py:63 new request
[2020-05-21 14:41:48,347] INFO basehttp.py:154 "GET /BlogView/ HTTP/1.1" 200 87809
[2020-05-21 14:42:17,079] WARNING urls.py:63 new request
[2020-05-21 14:42:17,870] ERROR views.py:424 Error (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials ef13sm4976887ejb.24 - gsmtp') while submitting email to carlo.folini@hotmail.com.
Traceback (most recent call last):
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\newsletter\views.py", line 421, in form_valid
    self.subscription.send_activation_email(action=self.action)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\newsletter\models.py", line 361, in send_activation_email
    message.send()
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\mail\message.py", line 291, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\mail\backends\smtp.py", line 103, in send_messages
    new_conn_created = self.open()
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\mail\backends\smtp.py", line 70, in open
    self.connection.login(self.username, self.password)
  File "C:\Program Files\Python38\lib\smtplib.py", line 734, in login
    raise last_exception
  File "C:\Program Files\Python38\lib\smtplib.py", line 723, in login
    (code, resp) = self.auth(
  File "C:\Program Files\Python38\lib\smtplib.py", line 646, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials ef13sm4976887ejb.24 - gsmtp')
[2020-05-21 14:42:17,977] INFO basehttp.py:154 "POST /newsletter/newsletter-del-viale-della-formica/subscribe/ HTTP/1.1" 200 11132
[2020-05-21 14:43:31,639] WARNING urls.py:63 new request
[2020-05-21 14:43:32,429] ERROR views.py:424 Error (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials b11sm4941163ejl.3 - gsmtp') while submitting email to carlo.folini@hotmail.com.
Traceback (most recent call last):
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\newsletter\views.py", line 421, in form_valid
    self.subscription.send_activation_email(action=self.action)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\newsletter\models.py", line 361, in send_activation_email
    message.send()
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\mail\message.py", line 291, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\mail\backends\smtp.py", line 103, in send_messages
    new_conn_created = self.open()
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\mail\backends\smtp.py", line 70, in open
    self.connection.login(self.username, self.password)
  File "C:\Program Files\Python38\lib\smtplib.py", line 734, in login
    raise last_exception
  File "C:\Program Files\Python38\lib\smtplib.py", line 723, in login
    (code, resp) = self.auth(
  File "C:\Program Files\Python38\lib\smtplib.py", line 646, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials b11sm4941163ejl.3 - gsmtp')
[2020-05-21 14:43:32,502] INFO basehttp.py:154 "POST /newsletter/newsletter-del-viale-della-formica/subscribe/ HTTP/1.1" 200 11132
[2020-05-21 14:43:33,378] WARNING urls.py:63 new request
[2020-05-21 14:43:33,389] INFO basehttp.py:154 "GET /static/images/favicon.ico HTTP/1.1" 200 15086
[2020-05-21 14:46:16,317] WARNING urls.py:63 new request
[2020-05-21 14:46:17,769] INFO basehttp.py:154 "GET /BlogView/ HTTP/1.1" 200 87809
[2020-05-21 14:46:20,959] WARNING urls.py:63 new request
[2020-05-21 14:46:21,779] ERROR views.py:424 Error (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials h5sm4823238ejg.124 - gsmtp') while submitting email to carlo.folini@hotmail.com.
Traceback (most recent call last):
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\newsletter\views.py", line 421, in form_valid
    self.subscription.send_activation_email(action=self.action)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\newsletter\models.py", line 361, in send_activation_email
    message.send()
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\mail\message.py", line 291, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\mail\backends\smtp.py", line 103, in send_messages
    new_conn_created = self.open()
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\mail\backends\smtp.py", line 70, in open
    self.connection.login(self.username, self.password)
  File "C:\Program Files\Python38\lib\smtplib.py", line 734, in login
    raise last_exception
  File "C:\Program Files\Python38\lib\smtplib.py", line 723, in login
    (code, resp) = self.auth(
  File "C:\Program Files\Python38\lib\smtplib.py", line 646, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials h5sm4823238ejg.124 - gsmtp')
[2020-05-21 14:46:21,839] INFO basehttp.py:154 "POST /newsletter/newsletter-del-viale-della-formica/subscribe/ HTTP/1.1" 200 11132
[2020-05-21 16:10:42,966] WARNING urls.py:63 new request
[2020-05-21 16:10:42,970] WARNING urls.py:76 >>>>>>>>>>>SERVER_TYPEDEVHOME
[2020-05-21 16:10:42,979] WARNING urls.py:84 >>>>>>>>>>>Error Base Url:http://127.0.0.1:8000
[2020-05-21 16:10:44,558] INFO basehttp.py:154 "POST /newsletter/newsletter-del-viale-della-formica/subscribe/ HTTP/1.1" 302 0
[2020-05-21 16:10:44,562] WARNING urls.py:63 new request
[2020-05-21 16:10:44,885] INFO basehttp.py:154 "GET /newsletter/newsletter-del-viale-della-formica/subscribe/email-sent/ HTTP/1.1" 200 11095
[2020-05-24 21:36:28,218] WARNING urls.py:63 new request
[2020-05-24 21:36:28,229] WARNING urls.py:76 >>>>>>>>>>>SERVER_TYPEDEVHOME
[2020-05-24 21:36:28,236] WARNING urls.py:84 >>>>>>>>>>>Error Base Url:http://127.0.0.1:8000
[2020-05-24 21:36:28,289] INFO basehttp.py:154 "GET / HTTP/1.1" 301 0
[2020-05-24 21:36:28,326] WARNING urls.py:63 new request
[2020-05-24 21:36:31,207] INFO basehttp.py:154 "GET /BlogView/ HTTP/1.1" 200 87809
[2020-05-24 21:36:31,566] WARNING urls.py:63 new request
[2020-05-24 21:36:31,577] INFO basehttp.py:154 "GET /static/images/LogoVialeBianco2019.png HTTP/1.1" 304 0
[2020-05-24 21:36:51,684] WARNING urls.py:63 new request
[2020-05-24 21:36:52,384] ERROR log.py:222 Internal Server Error: /newsletter/newsletter-del-viale-della-formica/subscribe/
Traceback (most recent call last):
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\newsletter\views.py", line 459, in dispatch
    return super(SubscribeRequestView, self).dispatch(
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\newsletter\views.py", line 155, in dispatch
    return super(ProcessUrlDataMixin, self).dispatch(*args, **kwargs)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\views\generic\edit.py", line 142, in post
    return self.form_valid(form)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\newsletter\views.py", line 421, in form_valid
    self.subscription.send_activation_email(action=self.action)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\newsletter\models.py", line 361, in send_activation_email
    message.send()
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\mail\message.py", line 291, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django_ses\__init__.py", line 159, in send_messages
    rate_limit = self.get_rate_limit()
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django_ses\__init__.py", line 249, in get_rate_limit
    quota_dict = self.connection.get_send_quota()
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\boto\ses\connection.py", line 341, in get_send_quota
    return self._make_request('GetSendQuota')
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\boto\ses\connection.py", line 119, in _make_request
    self._handle_error(response, body)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\boto\ses\connection.py", line 177, in _handle_error
    raise ExceptionToRaise(response.status, exc_reason, body)
boto.exception.BotoServerError: BotoServerError: 403 Forbidden
<ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidClientTokenId</Code>
    <Message>The security token included in the request is invalid.</Message>
  </Error>
  <RequestId>01f2cc7a-ff9d-4457-9d89-be672a0a2511</RequestId>
</ErrorResponse>

[2020-05-24 21:36:52,419] ERROR basehttp.py:154 "POST /newsletter/newsletter-del-viale-della-formica/subscribe/ HTTP/1.1" 500 136075
[2020-05-24 21:36:53,055] WARNING urls.py:63 new request
[2020-05-24 21:36:53,074] WARNING log.py:222 Not Found: /favicon.ico
[2020-05-24 21:36:53,078] WARNING basehttp.py:154 "GET /favicon.ico HTTP/1.1" 404 2526
[2020-05-24 21:46:41,160] WARNING urls.py:63 new request
[2020-05-24 21:46:41,206] WARNING urls.py:76 >>>>>>>>>>>SERVER_TYPEDEVHOME
[2020-05-24 21:46:41,208] WARNING urls.py:84 >>>>>>>>>>>Error Base Url:http://127.0.0.1:8000
[2020-05-24 21:46:41,272] INFO basehttp.py:154 "GET / HTTP/1.1" 301 0
[2020-05-24 21:46:41,285] WARNING urls.py:63 new request
[2020-05-24 21:46:43,274] INFO basehttp.py:154 "GET /BlogView/ HTTP/1.1" 200 87809
[2020-05-24 21:46:57,894] WARNING urls.py:63 new request
[2020-05-24 21:46:58,521] ERROR log.py:222 Internal Server Error: /newsletter/newsletter-del-viale-della-formica/subscribe/
Traceback (most recent call last):
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\newsletter\views.py", line 459, in dispatch
    return super(SubscribeRequestView, self).dispatch(
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\newsletter\views.py", line 155, in dispatch
    return super(ProcessUrlDataMixin, self).dispatch(*args, **kwargs)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\views\generic\edit.py", line 142, in post
    return self.form_valid(form)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\newsletter\views.py", line 421, in form_valid
    self.subscription.send_activation_email(action=self.action)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\newsletter\models.py", line 361, in send_activation_email
    message.send()
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\mail\message.py", line 291, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django_ses\__init__.py", line 159, in send_messages
    rate_limit = self.get_rate_limit()
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django_ses\__init__.py", line 249, in get_rate_limit
    quota_dict = self.connection.get_send_quota()
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\boto\ses\connection.py", line 341, in get_send_quota
    return self._make_request('GetSendQuota')
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\boto\ses\connection.py", line 119, in _make_request
    self._handle_error(response, body)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\boto\ses\connection.py", line 177, in _handle_error
    raise ExceptionToRaise(response.status, exc_reason, body)
boto.exception.BotoServerError: BotoServerError: 403 Forbidden
<ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidClientTokenId</Code>
    <Message>The security token included in the request is invalid.</Message>
  </Error>
  <RequestId>721652c8-1a3b-434c-9dcf-8120e3268a69</RequestId>
</ErrorResponse>

[2020-05-24 21:46:58,574] ERROR basehttp.py:154 "POST /newsletter/newsletter-del-viale-della-formica/subscribe/ HTTP/1.1" 500 136090
[2020-05-24 21:50:25,804] WARNING urls.py:63 new request
[2020-05-24 21:50:25,809] WARNING urls.py:76 >>>>>>>>>>>SERVER_TYPEDEVHOME
[2020-05-24 21:50:25,819] WARNING urls.py:84 >>>>>>>>>>>Error Base Url:http://127.0.0.1:8000
[2020-05-24 21:50:26,675] ERROR log.py:222 Internal Server Error: /newsletter/newsletter-del-viale-della-formica/subscribe/
Traceback (most recent call last):
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\newsletter\views.py", line 459, in dispatch
    return super(SubscribeRequestView, self).dispatch(
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\newsletter\views.py", line 155, in dispatch
    return super(ProcessUrlDataMixin, self).dispatch(*args, **kwargs)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\views\generic\edit.py", line 142, in post
    return self.form_valid(form)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\newsletter\views.py", line 421, in form_valid
    self.subscription.send_activation_email(action=self.action)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\newsletter\models.py", line 361, in send_activation_email
    message.send()
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\mail\message.py", line 291, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django_ses\__init__.py", line 159, in send_messages
    rate_limit = self.get_rate_limit()
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django_ses\__init__.py", line 249, in get_rate_limit
    quota_dict = self.connection.get_send_quota()
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\boto\ses\connection.py", line 341, in get_send_quota
    return self._make_request('GetSendQuota')
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\boto\ses\connection.py", line 119, in _make_request
    self._handle_error(response, body)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\boto\ses\connection.py", line 177, in _handle_error
    raise ExceptionToRaise(response.status, exc_reason, body)
boto.exception.BotoServerError: BotoServerError: 403 Forbidden
<ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidClientTokenId</Code>
    <Message>The security token included in the request is invalid.</Message>
  </Error>
  <RequestId>fb5bb0ff-faaa-4477-b287-8ff930d7d4a5</RequestId>
</ErrorResponse>

[2020-05-24 21:50:26,729] ERROR basehttp.py:154 "POST /newsletter/newsletter-del-viale-della-formica/subscribe/ HTTP/1.1" 500 135910
[2020-05-24 21:52:23,638] WARNING urls.py:63 new request
[2020-05-24 21:52:24,155] ERROR log.py:222 Internal Server Error: /newsletter/newsletter-del-viale-della-formica/subscribe/
Traceback (most recent call last):
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\newsletter\views.py", line 459, in dispatch
    return super(SubscribeRequestView, self).dispatch(
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\newsletter\views.py", line 155, in dispatch
    return super(ProcessUrlDataMixin, self).dispatch(*args, **kwargs)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\views\generic\edit.py", line 142, in post
    return self.form_valid(form)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\newsletter\views.py", line 421, in form_valid
    self.subscription.send_activation_email(action=self.action)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\newsletter\models.py", line 361, in send_activation_email
    message.send()
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\mail\message.py", line 291, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django_ses\__init__.py", line 159, in send_messages
    rate_limit = self.get_rate_limit()
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django_ses\__init__.py", line 249, in get_rate_limit
    quota_dict = self.connection.get_send_quota()
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\boto\ses\connection.py", line 341, in get_send_quota
    return self._make_request('GetSendQuota')
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\boto\ses\connection.py", line 119, in _make_request
    self._handle_error(response, body)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\boto\ses\connection.py", line 177, in _handle_error
    raise ExceptionToRaise(response.status, exc_reason, body)
boto.exception.BotoServerError: BotoServerError: 403 Forbidden
<ErrorResponse xmlns="http://ses.amazonaws.com/doc/2010-12-01/">
  <Error>
    <Type>Sender</Type>
    <Code>InvalidClientTokenId</Code>
    <Message>The security token included in the request is invalid.</Message>
  </Error>
  <RequestId>a8f1c551-d6d7-469a-a8b6-2d072ec1505d</RequestId>
</ErrorResponse>

[2020-05-24 21:52:24,202] ERROR basehttp.py:154 "POST /newsletter/newsletter-del-viale-della-formica/subscribe/ HTTP/1.1" 500 135912
[2020-06-01 10:04:19,675] WARNING urls.py:63 new request
[2020-06-01 10:04:19,731] WARNING urls.py:76 >>>>>>>>>>>SERVER_TYPEDEVHOME
[2020-06-01 10:04:19,737] WARNING urls.py:84 >>>>>>>>>>>Error Base Url:http://127.0.0.1:8000
[2020-06-01 10:04:19,793] INFO basehttp.py:154 "GET / HTTP/1.1" 301 0
[2020-06-01 10:04:19,803] WARNING urls.py:63 new request
[2020-06-01 10:04:21,376] WARNING views.py:100 New content, new file created
[2020-06-01 10:04:28,694] ERROR log.py:222 Internal Server Error: /BlogView/
Traceback (most recent call last):
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'cookielaw_banner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Progetti\SitiWeb\IlViale\BlogView\views.py", line 191, in index
    return render(
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\template\loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\template\base.py", line 156, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\template\base.py", line 194, in compile_nodelist
    return parser.parse()
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Progetti\SitiWeb\IlViale\envIlViale\lib\site-packages\django\template\base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 184: 'cookielaw_banner'. Did you forget to register or load this tag?
[2020-06-01 10:04:28,728] ERROR basehttp.py:154 "GET /BlogView/ HTTP/1.1" 500 281669
[2020-06-01 10:04:29,470] WARNING urls.py:63 new request
[2020-06-01 10:04:29,488] WARNING log.py:222 Not Found: /favicon.ico
[2020-06-01 10:04:29,492] WARNING basehttp.py:154 "GET /favicon.ico HTTP/1.1" 404 2526
[2020-06-01 10:05:50,329] WARNING urls.py:63 new request
[2020-06-01 10:05:50,333] WARNING urls.py:76 >>>>>>>>>>>SERVER_TYPEDEVHOME
[2020-06-01 10:05:50,344] WARNING urls.py:84 >>>>>>>>>>>Error Base Url:http://127.0.0.1:8000
[2020-06-01 10:05:52,029] INFO basehttp.py:154 "GET /BlogView/ HTTP/1.1" 200 88625
[2020-06-01 10:05:52,086] WARNING urls.py:63 new request
[2020-06-01 10:05:52,087] WARNING urls.py:63 new request
[2020-06-01 10:05:52,102] INFO basehttp.py:154 "GET /static/cookielaw/css/cookielaw.css HTTP/1.1" 200 340
